### ISSUE TITLE
Cannot get any URL

### ISSUE THREAD

**Issue by Abhishek0116** [SoundByteOSS/youtube-extractor#27]
I used same example given with this plugin but it's not working. I got following error

`
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:222:5)
#1      _MyAppState.youtubeVideoUrls (package:video_player_demo/main.dart:44:41)
<asynchronous suspension>
#2      _MyAppState.initState (package:video_player_demo/main.dart:71:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
#9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
#10     BuildOwner.buildScope (package:flutter/<…>
`

**Comment by Trojan9** [comment]
same here

**Comment by wackyapps** [comment]
same error appearing for me
https://www.loom.com/share/24529b335a1f47bd9865c9cc9785cb8e

**Comment by sanda0** [comment]
same error

I/flutter ( 1548): https://youtu.be/_2xZ71BodIk
V/AudioManager( 1548): playSoundEffect   effectType: 0
E/flutter ( 1548): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: No element
E/flutter ( 1548): #0      List.first (dart:core-patch/growable_array.dart:250:5)
E/flutter ( 1548): #1      _HomeState._getLinks (package:y2v/screens/home.dart:95:60)
E/flutter ( 1548): <asynchronous suspension>
E/flutter ( 1548): #2      _HomeState.build.<anonymous closure> (package:y2v/screens/home.dart:47:19)
E/flutter ( 1548): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter ( 1548): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter ( 1548): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter ( 1548): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter ( 1548): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter ( 1548): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter ( 1548): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter ( 1548): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter ( 1548): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 1548): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter ( 1548): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter ( 1548): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter ( 1548): #15     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 1548): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1548): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 1548): #18     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter ( 1548): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter ( 1548):

**Comment by Hexer10** [comment]
@wijewardhane this project hasn't received any update since a while, but you can try my package which was rewritten from scratch https://pub.dev/packages/youtube_explode_dart

**Comment by mikiyasET** [comment]
@Hexer10 Your package doesn't provide urls for audio it just show infos

**Comment by Hexer10** [comment]
> @Hexer10 Your package doesn't provide urls for audio it just show infos

You can, just read the readme correctly, if you really can't figure it out, contact me
