### ISSUE TITLE
not extract video dash

### ISSUE THREAD

**Issue by shailendra-rajpoot** [SoundByteOSS/youtube-extractor#29]
show error

D/libc-netbsd(23374): getaddrinfo: www.youtube.com get result from proxy gai_error = 0
E/flutter (23374): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'group' was called on null.
E/flutter (23374): Receiver: null
E/flutter (23374): Tried calling: group(0)
E/flutter (23374): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (23374): #1      YouTubeExtractor._getVideoPlayerContextAsync (package:youtube_extractor/youtube_extractor.dart:228:14)
E/flutter (23374): <asynchronous suspension>
E/flutter (23374): #2      YouTubeExtractor.getMediaStreamsAsync (package:youtube_extractor/youtube_extractor.dart:38:31)
E/flutter (23374): #3      main (package:flick_player/main.dart:7:36)
E/flutter (23374): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (23374): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (23374): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (23374): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (23374): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (23374): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (23374): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (23374): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23374):

**Comment by zekkontro** [comment]
mee too. Help me Please

**Comment by fede1295** [comment]
Result of this RegExp(r"yt\.setConfig\({'PLAYER_CONFIG':.+?\}\);" is empty, this causes the exception... 
Anyone knows what are these configs?
