### ISSUE TITLE
the method 'group' was called on null again

### ISSUE THREAD

**Issue by zaifullahbandung** [SoundByteOSS/youtube-extractor#6]
this is the error

E/flutter (24762): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (24762): NoSuchMethodError: The method 'group' was called on null.
E/flutter (24762): Receiver: null
E/flutter (24762): Tried calling: group(1)
E/flutter (24762): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (24762): #1      PlayerSourceParser.parseCipherOperations (package:youtube_extractor/src/internal/parsers/player_source_parser.dart:23:27)
E/flutter (24762): #2      YouTubeExtractor._getVideoPlayerSourceAsync (package:youtube_extractor/youtube_extractor.dart:298:29)
E/flutter (24762): <asynchronous suspension>
E/flutter (24762): #3      YouTubeExtractor.getMediaStreamsAsync (package:youtube_extractor/youtube_extractor.dart:73:19)
E/flutter (24762): <asynchronous suspension>
E/flutter (24762): #4      test (package:chewie_sample/geturl.dart:8:40)
E/flutter (24762): <asynchronous suspension>
E/flutter (24762): #5      MyApp.build (package:chewie_sample/main.dart:15:5)
E/flutter (24762): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
E/flutter (24762): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
E/flutter (24762): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (24762): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
E/flutter (24762): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
E/flutter (24762): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
E/flutter (24762): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
E/flutter (24762): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
E/flutter (24762): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
E/flutter (24762): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (24762): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (24762): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (24762): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by zaifullahbandung** [comment]
please help me for fix the error
